version: '2'
services:
    dhsknowledgemanagement-app:
        image: dhsknowledgemanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dhsknowledgemanagement-mysql:3306/dhsknowledgemanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dhsknowledgemanagement-mysql:
        extends:
            file: mysql.yml
            service: dhsknowledgemanagement-mysql
